version: "3.3"
services:
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: main_user
      MONGO_INITDB_ROOT_PASSWORD: secret